baseURL = "https://sanskrit-coders.github.io/"
languageCode = "en-us"
title = "संस्कृत-साङ्गणकाः Sanskrit Programmers"
theme = "sanskrit-documentation-theme-hugo"
publishDir = "build_github"
disablePathToLower = true


[outputs]
  home = ["HTML", "RSS", "JSON", "CSV"]
  section = ["HTML", "RSS", "JSON"]

[params]
  githubEditMePathBase = "https://github.com/sanskrit-coders/sanskrit-coders.github.io/edit/hugo-source/content/"
  contactLink = "https://github.com/sanskrit-coders/sanskrit-coders.github.io/issues/new"
  build_img = "https://github.com/sanskrit-coders/sanskrit-coders.github.io/actions/workflows/build.yml/badge.svg"
  build_url = "https://github.com/sanskrit-coders/sanskrit-coders.github.io/actions/workflows/build.yml"
  env = "production"
  disqusShortcode = "sanskrit-coders-site"

[markup.goldmark.renderer]
   unsafe = true

[markup.highlight]
  anchorLineNos = false
  codeFences = true
  guessSyntax = false
  hl_Lines = ''
  lineAnchors = ''
  lineNoStart = 1
  lineNos = true
  lineNumbersInTable = true
  noClasses = true
  style = 'friendly'
  tabWidth = 2
